# Generated by Django 2.0.6 on 2018-06-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180629_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='to_relations',
            new_name='to_relations_users',
        ),
    ]
