# Generated by Django 2.0.6 on 2018-06-30 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180629_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='to_relations_users',
            field=models.ManyToManyField(blank=True, related_name='from_relation_users', related_query_name='from_relation_user', through='members.Relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
