# Generated by Django 2.0.6 on 2018-07-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20180630_0637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('from_user', 'to_user', 'relation_type')},
        ),
    ]
